### ISSUE TITLE
Handle if we are in live acquisition mode in Autofocus

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#709] opened 2023-12-06 16:59 UTC
Right now we have to stop live acquisition mode to launch autofocus. Make it so we automatically stop live acquisition mode, run autofocus, restart live acquisition mode if this is the case.

**Comment by AdvancedImagingUTSW** [comment] 2023-12-27 13:47
@annie-xd-wang, this is close to functional, but not. Any chance you could look at the branch that is linked to this? Essentially, we now pass if we should return to the live acquisition mode as a kwarg, but after running the autofocus routine (`autofocus.run`), I'm not sure what the best way to create a wait statement for the autofocus to complete. I assume it may be one or two lines of code, but everything I have tried doesn't work as intended because the autofocus routine is launched as a asynchronous thread.

**Comment by annie-xd-wang** [comment] 2023-12-27 16:25
Sure, I will look into it.

**Comment by AdvancedImagingUTSW** [comment] 2024-02-02 20:38
This was fixed in #799

**Closed as completed by AdvancedImagingUTSW** 2024-02-02 20:38 UTC
Labels: enhancement, low priority
